### ISSUE TITLE
Heatmap doesnt show up

### ISSUE THREAD

**Issue by andreevg04** [Pharmaco-OmicsLab/EasyPubPlot#1] opened 2024-12-03 12:50 UTC
I tried to create a complex heatmap with over 70 samples, 3 groups and 20 measurements. The heatmap said at first that sample names didnt match, which they did, so I changed the column name in the metadata from PatientID to Sample and then no more error message. 
Nevertheless the heatmap just doesnt show.

**Comment by Pharmaco-OmicsLab** [comment] 2024-12-03 14:09
Dear @andreevg04 

First of all, thank you for reaching out and using our tool.

The error might be due to the inconsistency of the two required input data (likely, the sample names in the metadata and in the normalized intensity data did not match perfectly). In your case, for instance, the sample names were **`Patient 1`**, `Patient 2`, and `Patient 3` in the metadata, while in the normalized intensity data, they were **`Patient_1`**, `Patient 2`, and `Patient 3`. Note that **`Patient 1`** and **`Patient_1`** are considered different. Ensuring consistent naming between both datasets could resolve this error.

We simulated your scenario with 70 samples, 3 groups, and 20 features, and the heatmap worked as expected in our app. To get the best visualization, we recommend adjusting the width to 1000 and the height to 400 to scale your heatmap appropriately, similar to what is shown in the attached screenshot.
![image](https://github.com/user-attachments/assets/c4980575-eb72-441e-b8db-434dbd3c4c6b)

Here are the two pseudo data files. Please take a look. We hope this is helpful to you.
[HeatmapSimple_ExampleMetaData_Issue1.csv](https://github.com/user-attachments/files/17993827/HeatmapSimple_ExampleMetaData_Issue1.csv)
[HeatmapSimple_ExampleNormData_Issue1.csv](https://github.com/user-attachments/files/17993829/HeatmapSimple_ExampleNormData_Issue1.csv)

Please let us know if you have any other questions or issues.

Thank you again for your time and effort in using our tool.
Tien Nguyen.

**Comment by andreevg04** [comment] 2024-12-03 14:18
Thank you for the fast response, my patient IDs are pseudocodes for example A111111, A333333 etc. they are the same in the metadata and the normalized table. So I named the column name in the metadata Sample because that was the only way it wouldnt pop up the error that it doesnt match. 

I am plotting densities which might have values of 0 is that a possible issue?

**Comment by Pharmaco-OmicsLab** [comment] 2024-12-03 14:41
Dear @andreevg04 

Thank you so much for following up.

It seems unlikely that the `column names`, `sample names`, or the presence of `0 `values are causing the error. To help illustrate, we have included an updated version of the pseudo data, where we used `PatientID` as the column name, with sample names like `A111111` and `A333333`. This data also contained several `0` values. It worked as expected.
[HeatmapSimple_ExampleNormData_Issue1_v2.csv](https://github.com/user-attachments/files/17994613/HeatmapSimple_ExampleNormData_Issue1_v2.csv)
[HeatmapSimple_ExampleMetaData_Issue1_v2.csv](https://github.com/user-attachments/files/17994614/HeatmapSimple_ExampleMetaData_Issue1_v2.csv)

We hope this updated example is helpful for you. 

Please let us know if you have any other questions or issues.

Thank you once again for your time and effort in using our tool.

Warm regards,
Tien Nguyen

**Comment by andreevg04** [comment] 2024-12-05 11:09
I saw what the problem was. 
In the metadata when I made 2 groups: 1 was cancer type, 2 was IHC profile I got the error message. 
As soon as it was 1 group everything was fine and I got the nice graph

**Comment by Pharmaco-OmicsLab** [comment] 2024-12-06 09:05
Dear @andreevg04 

Thank you so much for your follow-up message.

We are happy you solved the problem and got a great result!

In this release, the heatmap module was designed to work with a straightforward metadata structure (i.e., one group level in the metadata). We’re currently working on an advanced version of the heatmap module that will support more complex study designs. This will be released in the next update.

Best regards,
Tien Nguyen

**Closed as completed** 2024-12-11 05:09 UTC
